### ISSUE TITLE
Never set line/col information in GrammarError message

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#102]
Look for all `new GrammarException` and make them consistent.  Fix the tests.

Is anyone relying on the message format downstream?

**Comment by StoneCypher** [comment]
I am, but, I'm happy to let it go in the name of uniformity

**Comment by hildjj** [comment]
are you parsing them, or are you just using them in unit tests?

**Comment by hildjj** [comment]
See https://github.com/rse/pegjs-util#cooked-error-reporting .  Should we provide a cooked method on GrammarError?

**Comment by StoneCypher** [comment]
I am parsing them, but I would actually prefer uniformity to keeping as-is.  

I have never seen anyone else using them except to export them as a string

**Comment by hildjj** [comment]
`GrammarError` does not extend `Error` for some reason.  Is this because there are JS implementations that don't include `Error` or something?  I bet if so, none of them support `class`, so I think this is either an oversight on an anachronism.

Unless someone has a reason otherwise, I'll fix that along with this bug, and replace the awkward call to `captureStackTrace` with a call to `super`.

**Comment by Mingun** [comment]
This is definitely an error introduced [during migration](https://github.com/pegjs/pegjs/5822596ab8f9f9b659a108e0a7f69d403cc86e41) to ES6 `class`. In ES5 it was subclassed
