### ISSUE TITLE
Configure CI to disallow warnings so that the local build doesn't trip on little things

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#125]
***This is not a suggestion that warnings are okay***

Ergonomically, it's hard to work when warnings are errors.  Right now, I have to fix the `lint` errors before I proceed.  (Actually, the reason I forgot the linter in the build was I left it out because it was interfering with my real work, over things like the wrong quote type.)

I am not saying that's minor!  It's important.

However, the reason we have warnings vs errors is to establish tiers of importance.  

I am of the opinion that ***only things which cause actual wrongness should halt the build***.

In order to dovetail this with wanting warnings to be enforced, my own libraries follow the practice of adding a command line flag to halt on warnings, then treating everything that isn't a bug as a warning.

Following that, I have continuous integration forbid warnings.  That way, the warnings never get in, but the developers can be trusted with the easier and more convenient ergonomic experience.

My goal is to land #107 without this, and follow this up same-day.  It's just a single flag, but the work in #107 is sufficiently complex that I want to dawdle until that's over, if that's okay.

**Comment by StoneCypher** [comment]
This was intimated on the [currently-last comment](https://github.com/peggyjs/peggyjs-eslint-config/issues/1#issuecomment-827890434) of issue #1

**Comment by hildjj** [comment]
I'm open to a PR on this once we land 107.  Importantly, I'll still want vscode-eslint to show squigglies locally.  I assume that it will still do so for warnings.

**Comment by StoneCypher** [comment]
Yes, and, better than that.  It'll show red squigglies for errors, and yellow squigglies for convention violations.

Yellow squigglies for single quote, red squigglies for missing parenthesis.

This works for vscode, and this works for eslint.  I assume it'll work for your crossover plugin.  If it doesn't, I'll ditch it.

**Comment by StoneCypher** [comment]
well at least in the default color set, for all i know they're different in solarized bluefilter or monokai dusk mode or ex plus alpha super midnight edition or whatever theme the cool kids use this week
