### ISSUE TITLE
The name "Peggy" is confusing

### ISSUE THREAD

**Issue by jarble** [peggyjs/peggy#149]
There are at least two other parser generators with exactly the same name as this one:
* [Peggy](https://tanakh.github.io/Peggy/ ): A parser generator for Haskell
* [Peggy](https://github.com/eaburns/peggy): A parser generator for Go

Could this JavaScript parser generator be re-named to something less ambiguous, like "PeggyJS"?

**Comment by hildjj** [comment]
I'm not excited about changing, but let's see if you get a bunch of thumbs-up on your suggestion?

If we're going to change, we should do it sooner rather than later.
