### ISSUE TITLE
Try to match the first expression fails

### ISSUE THREAD

**Issue by MarcinZmudka** [peggyjs/peggy#153]
I have an expression:

```
Var
  = _ keyword: 'var' ?
    _ name: Name
    _ '=' 
    _ value: ( Number / Bool  / Value )
    {
     ...
    }
```
It tries to match Number but when it fails inside Number, the whole expression fails. It is not going to match Bool nor Value.
Have someone idea why is that?

Thanks for help

**Comment by Mingun** [comment]
Could you add to your message the `Number`, `Bool` and `Value` definitions?

**Comment by MarcinZmudka** [comment]
Thanks for answer. Unfortunately I cannot. 
Why if it fails inside `Number` it does not goes further to `Bool`?

**Comment by Mingun** [comment]
Are you using `expected()` or `error()` functions inside your `Number` rule? That functions immediately throws an SyntaxError, so there is no backtracking after them. If you need to backtrack, you should use semantic predicates to check conditions instead.

If you do not want to deal with tracer setup, you alternatively could try to add a temporal logging to your rule:
```peggy
Var
  = _ keyword: 'var' ?
    _ name: Name
    _ '=' 
    _ value: ( n:Number { console.log('Number parsed', n); return n; } / Bool  / Value )
    {
     ...
    }
```

**Comment by MarcinZmudka** [comment]
I use `... ! expression` inside Number. Do you think that matters?

**Comment by hildjj** [comment]
Using this complete peggy grammar, I'm seeing correct backtracking:

```peggy
Var
  = _ keyword: 'var' ?
    _ name: Name
    _ '=' 
    _ value: ( Number / Bool  / Value )
    {
     return {name, value}
    }

Name = $[a-z]i+
Number = !"0" n:$[0-9]+ { return parseInt(n, 10) }
Bool
  = "true"i
  / "false"i
Value = $[a-z0-9]i+

_ = [ \t]*
```

I used the `!` in Number to prevent leading zeros, and pushed numbers with leading zeros to be a Value (without numeric decoding).  So, the input `foo = 10` gives `{ name: 'foo', value: 10 }` and the input `foo = 010` gives: `{ name: 'foo', value: '010' }`.  You can see that it's backtracking in the trace from the second one:

```
1:1-1:1 rule.enter Var
1:1-1:1 rule.enter   _
1:1-1:1 rule.match   _
1:1-1:1 rule.enter   _
1:1-1:1 rule.match   _
1:1-1:1 rule.enter   Name
1:1-1:4 rule.match   Name
1:4-1:4 rule.enter   _
1:4-1:5 rule.match   _
1:6-1:6 rule.enter   _
1:6-1:7 rule.match   _
1:7-1:7 rule.enter   Number
1:7-1:7 rule.fail    Number
1:7-1:7 rule.enter   Bool
1:7-1:7 rule.fail    Bool
1:7-1:7 rule.enter   Value
1:7-1:10 rule.match   Value
1:1-1:10 rule.match Var
```

**Comment by MarcinZmudka** [comment]
Thanks guys for help. So i backtraced it. The `Number` wasn't failing. The `Number` expression matched incorrectly and that's why `Var` was failing.

**Comment by hildjj** [comment]
@MarcinZmudka would you mind closing this issue if you no longer need help?
