### ISSUE TITLE
Class 'SyntaxError' incorrectly implements interface 'Error'

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#155]
With the current `peg.d.ts`, I get this error when compiling typescript that uses peggy:

```
../../lib/peg.d.ts:345:9 - error TS2420: Class 'SyntaxError' incorrectly implements interface 'Error'.
  Type 'SyntaxError' is missing the following properties from type 'Error': name, message

345   class SyntaxError implements Error {
            ~~~~~~~~~~~


Found 1 error.
```

I think we might need to add:

```typescript
    name: string;
    message: string;
    stack?: string;
```

to the class, or change it to an interface?

**Comment by Mingun** [comment]
Just need to change `implements` to `extends` -- this is one of special cases in TypeScript, where you should extend interface with class instead of implementing it.

**Comment by hildjj** [comment]
Yes, that works.  I'll put a fix into the type testing patch I'm finishing up.
