### ISSUE TITLE
add github link in the official site

### ISSUE THREAD

**Issue by xialvjun** [peggyjs/peggy#156]
as the title

**Comment by camchenry** [comment]
@hildjj I believe this can be closed out? There are a few links to GitHub on the website.

1. In the footer
    <img width="344" alt="Source code link to Peggy in website footer" src="https://user-images.githubusercontent.com/1514176/180621455-0791f5e6-228f-4d62-b1df-59343ac9f464.png">
2. On the "Development" page 
    <img width="374" alt="Link to the Peggy source code on the development page" src="https://user-images.githubusercontent.com/1514176/180621467-4b9df030-3c8c-483b-9f49-a7ae495cf25d.png">

**Comment by hildjj** [comment]
I was thinking maybe we should make it a little more in-your-face, like a [fork me on github ribbon](https://github.blog/2008-12-19-github-ribbons/) in the upper right corner of every page.

**Comment by hildjj** [comment]
Anyone who is still annoyed by this, please re-open, or send a PR.
