### ISSUE TITLE
Add -c / --config CLI option

### ISSUE THREAD

**Issue by Fluvf** [peggyjs/peggy#161]
From [pegjs master](https://github.com/pegjs/pegjs/blob/master/docs/guides/command-line.md):

> Configuration file
> 
> If you provide a configuration file (via -c or --config) then you can use all the options used by the PEG.js API, as well as:
> 
> * input — The grammar used as the input file
> * output — Output's generated parser to the provided destination
> 
>     1. Will throw if neither are strings, or the input has already been provided
>     2. the output option for the compiler is not usable from the config

> Command Line Options
> ...
> * -c, --config — file with additional options (in JSON or JavaScript) to pass to peg.generate

Writing and maintaining `pegjs -c config.json` rather than `peggy --extra-options-file options.json parser.pegjs` is nicer, especially with longer file paths and possible renames.

After a quick look, this seems to have been implemented in pegjs over these commits:
https://github.com/pegjs/pegjs/commit/0ed8c6f89a37dad7883680af64bc99641c54823e
https://github.com/pegjs/pegjs/commit/b6bc0d905e8c1a1c9cdb825d03980a06a668f5b8
https://github.com/pegjs/pegjs/commit/8b43c8419f566267a65620d1a62d7be60925fd1d

I myself do not need / use `.js` config files, but I can see the utility in the functionality.

**Comment by hildjj** [comment]
The CLI is getting a rewrite in 1.3, will revisit this in that work.
