### ISSUE TITLE
module example

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#177]
I'm having trouble using peggy in a project that is `"type": "module"` in package.json.  This works:

```js
import peggy from "peggy";
```

but typescript complains:

```
error TS1192: Module '"[path]/peggy/lib/peg"' has no default export.
```

This works:

```js
import * as p from "peggy";
const peggy = p.default;
```

but typescript complains:

```
error TS2339: Property 'default' does not exist on type 'typeof import("[path]/peggy/lib/peg")'.
```

This works in a .ts file:

```ts
import * as peggy from "peggy";
```

I feel like I figured this out once already, but didn't put it in the docs.

**Comment by hildjj** [comment]
Adding this to tsconfig.json worked:

```json
{
  "allowSyntheticDefaultImports": true
}
```

with:

```js
import peggy from "peggy";
```

**Comment by jeanbmar** [comment]
Using ESM JavaScript without TS, import is broken as well:

```js
import * as peggy from 'peggy';
peggy.generate('');

// TypeError: peggy.generate is not a function
```

**Comment by hildjj** [comment]
This is in the docs now.
