### ISSUE TITLE
Make all links (home, documentation, etc.) in the online version open in new tabs

### ISSUE THREAD

**Issue by zocky** [peggyjs/peggy#191]
Clicking on "documentation" navigates away from the online editor, and without saved state, that can mean losing work. Simply adding target="_blank" to the links will fix this.

**Comment by hildjj** [comment]
See also #186

**Comment by hildjj** [comment]
I think I'd prefer to just save the state adequately.

**Comment by hildjj** [comment]
I've decided I don't want this.  Use your browser's facility for opening a link in a new tab.  For me, it's cmd-click.
