### ISSUE TITLE
Reusing same pattern in a rule

### ISSUE THREAD

**Issue by jcubic** [peggyjs/peggy#194]
Here is an example of grammar that I would like to have:

```
heredoc = "<<<" marker:[\w]+ "\n" text:[\s\S]+ "\n" marker {
    return text.join('');
}
```

Right now it doesn't work but It would be nice to be able to use `marker` later in the rule. So I properly parse:
```ruby
<<<HELLO
1
2
3
HELLO
```

**Comment by Mingun** [comment]
This is trivially can be implemented by this grammar:
```pegjs
heredoc = "<<<" begin:marker "\n" @$_+ "\n" end:marker (
	&{ return begin === end; }
  / '' { error(`Expected matched marker "${begin}", but marker "${end}" was found`); }
);
_ = (!"\n" .);
marker 'Marker' = $_+;
```
I do not think that we need a special case for handling such situations unless someone can give reasonable arguments. For example, it can be hard to customize error message. Of course, you can try to make a PR realizing this feature.

Also, remember, that peggy does not use RegExps in their grammar to match symbols, constructions like `[\s\S]` will not work

**Comment by jcubic** [comment]
This seems to do the job:
```pegjs
heredoc = "<<<" begin:marker "\n" text:$($marker_char+ "\n")+ end:marker (
    &{ return begin === end; }
  / '' { error(`Expected matched marker "${begin}", but marker "${end}" was found`); }
) {
	return {
    	type: 'literal',
        value: text
   };
}
marker_char = (!"\n" .);
marker 'Marker' = $marker_char+;
```

**Comment by jcubic** [comment]
Here is my playground on Codepen https://codepen.io/jcubic/pen/NWvGmjv it should generate JavaScript code.

**Comment by jcubic** [comment]
This is becoming really complex and not so trivial to create. Maybe it's worth adding something like `start:marker ... end:start` (or some other syntax) that will allow back-references.

**Comment by hildjj** [comment]
Reference full feature request: https://github.com/pegjs/pegjs/issues/669

**Comment by jcubic** [comment]
That one is different because it was for different rules as array raw data. That one can be solved by using a validator/option.

But here you reference the pattern in the same rule at runtime, the value user uses not the one I've hardcoded in the grammar.

**Comment by jcubic** [comment]
I'm fine with this approach If you don't think it's a good idea to add this feature then you can close.

**Comment by hildjj** [comment]
Let's keep it open a few more days in case someone else thinks it's a great idea and doesn't like the work-around.

**Comment by jcubic** [comment]
@Mingun I again needed to add validation with error (now I fully understand how this works), but I think that your example is not documented. The README don't shows that you can use `{}` anywhere in the code and that you can use this pattern:

```
name:(rule / '' { error('xxx') })
```

Are there any other patterns like this? If yes then they should be documented separately (maybe on Wiki list of useful single rule examples on one page), no one have time to read full grammar to search for patterns that you can use.
