### ISSUE TITLE
Parsing a string with "boundaries"

### ISSUE THREAD

**Issue by jonathanbp** [peggyjs/peggy#209]
Hello. 

I have had trouble coming up with a grammar for parsing a string that has a specific char at its "boundaries" in a greater path-like structure but which may also contain the boundary char internally. 

So if the boundary char is `*` I need to pick out `*foobar*` in e.g. `/foo/*foobar*/bar`. My problem is that the `*foobar*` string may also contain the "boundary char" e.g. `*foo*bar*` so I cant use a negative char range for the parsing of the token between the `/`s.

Is it possible to do this with a PEG? And apologies if this is not the place for questions like this.

**Comment by Mingun** [comment]
How you can understand that specific char is not boundary, but an internal char? Your example is probably a degenerate case, have you more generic examples or maybe formal description?

**Comment by jonathanbp** [comment]
The `*`s are prefix and suffix of the string I'm parsing and indicate that the current path element is a specific type of element, but the `*` character can also occur inside the string. So if I have the string:

```
foo/*foo*bar*/bar
```

I'd like it parsed into a structure like;

```json
[{ "type": "normal", "text": "foo"}, { "type": "special", "text": "foo*bar"}, { "type": "normal", "text": "bar" }]
```

and the problem I'm having is how to allow the "special" strings to have `*` inside them. If I have a grammar that includes;

```
Elements = PathElement*

PathElement =
   Special
 / Normal

Normal =
  m:String "/" { return { type: "normal", text: m } }

Special =
  "*" m:String "*/"  { return { type: "special", text: m } }

String =
   $([^/]+)
```

The the `Special` rule won't apply since `String` will eat the last `*` and if I add the `*` to the `String` rule;

```
String =
   $([^/*]+)
```

then I can't have internal `*`s in my "Special" strings. So the question is whether there is a way to prevent the `String` rule from being too "greedy".

**Comment by Mingun** [comment]
Common answer for all such questions: check that thing you don't want not there and continue parsing, otherwise stop. In code:
```pegjs
Elements = PathElement*

PathElement =
   Special
 / Normal

Normal =
  m:String "/" { return { type: "normal", text: m } }

Special =
  "*" m:String EndOfSpecial  { return { type: "special", text: m } }

String =
   $(!EndOfSpecial [^/])+

// Don't forget to handle corner cases if they exist like
// special is the last element in the path:
//   /normal/*special*
// Such special handling need to be done there
EndOfSpecial = "*/"
```

**Comment by hildjj** [comment]
Taking mingun's grammar as a start, I came up with this, which gets all of the edge cases I could think of:

```pegjs
path = "/"? head:segment tail:("/" @segment)* "/"? { return [head, ...tail] }

segment
  = special
  / normal
  
special = "*" text:$special_char+ "*" { return { type: "special", text } }
normal = text:$[^/]+ { return { type: "normal", text } }

special_char
  = [^*]      // Any non-* is valid
  / "*" &[^/] // Following a * with anything but a / makes it a part of the text
```

**Comment by jonathanbp** [comment]
Great! Thanks a lot for your help, @Mingun and @hildjj - it is much appreciated.

**Comment by Mingun** [comment]
Anyway, check the examples yourself, because  @hildjj's variant parses `2 * (3 + 4)` as a valid `normal` segment, but probably this is unexpected. Another possible source of headaches -- `special_char` rule. It can parse `/*/*/` as a `special` value, but probably this is not what you want.

**Comment by hildjj** [comment]
This one is more fun than it looked. :)

Without more constraints, `2 * (3 + 4)` seems like a valid normal segment.  If we're talking real file paths, there are a list of characters that need to be escaped before they're valid in most shells....

`/*/*/` is a good corner case, which can be fixed by:

```pegjs
special_char
  = [^*/]     // Any non-* is valid, but stop when we get to a slash.
  / "*" &[^/] // Following a * with anything but a / makes it a part of the text
```
