### ISSUE TITLE
Bring typescript type definitions into this this repo

### ISSUE THREAD

**Issue by phpnode** [peggyjs/peggy#21]
PEG.js type definitions currently live in DefinitelyTyped - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pegjs

we should bring these into the peggy repo to prevent people from having to install the type definitions separately and to avoid the separate DefinitelyTyped workflow for contributors.

**Comment by hildjj** [comment]
In your PR, can you please clean up the `files` property in `package.json`, add a `.npmignore` by copying `.gitignore` and then adding `docs/`, etc., and test with `npm pack --dry-run`?
