### ISSUE TITLE
peg$FAILED logic seems really redundant

### ISSUE THREAD

**Issue by SNDST00M** [peggyjs/peggy#234]
`if s1 != FAILED` then `if s2 != FAILED` is crying out for some kind of stack array or more stateful, optimised solution :)

**Comment by Mingun** [comment]
Emm... Peggy even have [a special pass](https://github.com/peggyjs/peggy/blob/main/lib/compiler/passes/inference-match-result.js) to reduce excess code of pointless checks. You're find some checks that could be eliminated? Could you provide examples? What you suggest to generate instead?

**Comment by SNDST00M** [comment]
`if [s1, s2, s3, s4, ...].indexOf(FAILED) > -1` :)

**Comment by SNDST00M** [comment]
Eeeeeh I just figured out that it might be merely a pegjs issue, peggy is more succint e.g.

https://github.com/SNDST00M/vscode-textmate-languageservice/blob/v0.2.1/src/util/scopeSelectorParser.js
