### ISSUE TITLE
Better/any systax errors from grammar eval

### ISSUE THREAD

**Issue by sevenreeds** [peggyjs/peggy#235]
Hi

I have just started out with peggy. I have version 1.2.0.

I have a grammar file that has a global code section. I had a JavaScript syntax error in there but all that was reported was `SyntaxError: Unexpected string` along with a stack trace. The stack led men to the `return eval(ast.code);` line in "node_modules/peggy/lib/compiler/index.js" line 83.

The only way I could think of to debug the grammar was to copy the `ast.code` string into a temporary JavaScript file and look for errors reported by me IDE.

I am not a JavaScript wizard so I have no idea if there is a way other than `eval` to maybe pre-process code sections in a grammar and report per section issues?

__Edit__

... followup: to be fair, the error message was correct, I did have in invalid string under JS rules.  I have now played around a little more and see other specific errors generated but without any error location info.

**Comment by sevenreeds** [comment]
On third thought I will close this issue.  While the errors are not pinpoint accurate with location they are sufficient now that I have had to hunt a few down.  cheers

**Comment by Mingun** [comment]
Incoming 1.3.0 will contain a [sourcemap support](https://github.com/peggyjs/peggy/issues/163) so probably this will solve that issue.

**Comment by sevenreeds** [comment]
brilliant, looking forward to it. cheers
