### ISSUE TITLE
[Question] Including full match instead of first character in Expected error?

### ISSUE THREAD

**Issue by robodude666** [peggyjs/peggy#237]
Taking a simple grammar as an example:

```python
Expression = "foo" "\n" "bar"
```

the following input:

```
Foo
bar
```

results in the error message `Expected "foo" but "F" found.`

How would you instead produce an error message that states `Expected "foo" but "Foo" found.` ?

**Comment by robodude666** [comment]
@Mingun that's understandable. In the above scenario how would you do that?

Best I can think of then would be:

```javascript
Expression = @Foo "\n" @Bar
Foo
  = head:$[a-z]i+ {
    return head == 'foo' ? head : error(`Expected "foo" but "${head}" found.`)
  }
Bar
  = head:$[a-z]i+ {
    return head == 'bar' ? head : error(`Expected "bar" but "${head}" found.`)
  }
```

but that seems impractical. Is there a better way?

**Comment by Mingun** [comment]
Assumed, that all your expected values are strings, you can do something like this:
Grammar:
```pegjs
Expression = "foo" "\n" "bar"

// Special rule that used to give an "expected" value
Found = $[a-z]i+
```
Usage code:
```js
let parser = peggy.generate(grammar, {
  allowedStartRules: ["Expression", "Found"]
});
try {
  return parser.parse(input);
} catch (e) {
  if (e instanceof parser.SyntaxError) {
    // Reparse at error location using a special rule to get an actual value
    e.found = parser.parse(
      input.substring(e.location.start.offset),
      { startRule: "Found" }
    );
  }
  throw e;
}
```
Naturally, you can extract the "found" in any way convenient to you, just this seems to me the most elegant.

**Comment by hildjj** [comment]
Looks like we found a work-around.  Re-open if we can think of a more general approach, please.
