### ISSUE TITLE
Better documentation for cli

### ISSUE THREAD

**Issue by quinn-dougherty** [peggyjs/peggy#242]
Some pain points
- docs say `.js` or `.cjs` is a valid file for `--extra-options-file`, and gives an example with `module.exports = ...`. But the cli fails when you pass in a non-json file
- `-c` doesn't actually exist (in spite of documentation)
- It seems to me like `"output": ` flag in that `.json` wants me to specify a format, not a filename. but this isn't documented. 
- `-T`, `--test-file`, `--test` are considered by the cli to be an unknown option, in spite of documentation. I'm sure there are more like this. 

I'm on `1.2.0`

**Comment by quinn-dougherty** [comment]
> You may also specify an `input` field instead of using the command line

According to my testing, this isn't true. not specifying input but passing in `.json` makes the cli hang/run forever.

**Comment by H4M5TER** [comment]
it's weird that [it seems fine in the code](https://github.com/peggyjs/peggy/blob/ddb35b4a4ad8df4d3f315fcd79f96352b05d823e/bin/peggy.mjs#L105).
but it looks like this locally
```js

    case "--extra-options-file":
      nextArg();
      if (args.length === 0) {
        abort("Missing parameter of the --extra-options-file option.");
      }
      try {
        json = fs.readFileSync(args[0]);
      } catch (e) {
        abort("Can't read from file \"" + args[0] + "\".");
      }
      addExtraOptions(options, json);
      break;
```

**Comment by hildjj** [comment]
I think this is fixed in the 1.3 branch.  We might have updated the published docs too early, but this should be fixed when we publish 1.3.

**Comment by hildjj** [comment]
Looking again, yes, that's what happened.  We've gotten better about only putting doc changes into a feature branch, so this shouldn't happen again.

**Comment by hildjj** [comment]
Please re-test on v2.0.0?
