### ISSUE TITLE
Please more examples ...

### ISSUE THREAD

**Issue by heilingbrunner** [peggyjs/peggy#243]
Please provide more simple examples regarding to the documentation. The section 'Parsing Expression Types' could be better if the are some simple examples to get into the usage of the expression.

Thank you.

**Comment by hildjj** [comment]
I'm imagining an example for each type, showing a matching input and a non-matching input.  For example:

`"literal"`
`'literal'`
    Match exact literal string and return it. The string syntax is the same as in JavaScript. Appending i right after the literal makes the match case-insensitive.

Example: `top = "foo"i`
Matches: `foo`, `FOO`, `FoO`
Doesn't match: `fo`, `fooo`, `bar`

**Comment by Mingun** [comment]
Strongly speaking, `fooo` is matched by this _rule_, but the whole _grammar_ does not match (because grammar shouldn't leve unconsumed input)

**Comment by hildjj** [comment]
Let's decide if these are single rules or full grammars, I guess.  Either works for me as long as we're consistent.

**Comment by Mingun** [comment]
My vote for single rules with an explanation that examples just for rules, to see them in action you should pretend that actual grammar is
```pegjs
grammar = rule .*;
rule = <whatever>;
```
Links to live examples (or even embedded examples) also would be useful, but that the task for a web-site.

**Comment by hildjj** [comment]
I like the live playground idea, and since the docs are web-only now, that should work.  We could have one large grammar that has a rule for each section, with each rule in the allowedStartRules.

Maybe let's try that, and see what it feels like in practice before we finalize the `.*` approach?

**Comment by Mingun** [comment]
The `.*` approach is for dealing with situations like
```pegjs
foo = 'foo'i;
```
and input
```
foooo
```
The rule itself will match the beginning of this string, but to show this in action we should append `.*` to the end of rule, or just use `grammar` rule shown above. I think, it is important to highlight this particularity, because otherwise people can have a wrong impression that to match a keyword the grammar
```pegjs
keyword = 'keyword';
```
is enough (spoiler: it isn't, the right way to do that is to check that after a keyword there is a delimiter symbol or not an identifier symbol: 
```pegjs
keyword = 'keyword' !identifierPart;
```
)

I think more about supporting GET parameters in the https://peggy.js/online to embed a grammar and adding that links to a docs. I don't think that this should be a hard to implement.

**Comment by hildjj** [comment]
Can you take a look at https://raw.githack.com/hildjj/peggy/examples/docs/documentation.html please, and see what you think before I finish?  Go down to "Parsing Expression Types", and look at the first two.

**Comment by heilingbrunner** [comment]
These two examples are very simple. The inline try-test is nice, but not really required. I would like to see examples for the '&/! expression */+/?' and '&{predicate}'. 
I used your online version too. This is a very good learning tool.

**Comment by hildjj** [comment]
Please refresh the link above and see what you think?  I have now agreed with @Mingun about just matching the beginning, and have started returning `{ match: "stuff that matched", rest: "stuff after the match" }`

**Comment by hildjj** [comment]
This will show up with the next release.  I don't want to cherry-pick it onto the docs branch because the tooling needed to build it is only available after the next release.

**Comment by hildjj** [comment]
In the meantime, you can use https://raw.githack.com/peggyjs/peggy/main/docs/documentation.html

**Comment by heilingbrunner** [comment]
I looked at the examples and understood. They are very short, but now I understand how I can use e.g. predicates. I hadn't used that yet. Thank you.
