### ISSUE TITLE
Wiki is read only

### ISSUE THREAD

**Issue by jcubic** [peggyjs/peggy#247]
on [Projects Using Peggy](https://github.com/peggyjs/peggy/wiki/Projects-Using-Peggy) there is:

> Feel free to extend it if you know about more (just keep the list sorted alphabetically).

but I'm not allowed to edit the Wiki, it's restricted to contributors. You need to make it public.

I wanted to add my project, but not sure since the page shows PEG.js projects.

**Comment by hildjj** [comment]
I opened up write access on the wiki.  Re-open this if I didn't get it done correctly, please.
