### ISSUE TITLE
Broken link to unpkg

### ISSUE THREAD

**Issue by jarble** [peggyjs/peggy#263]
The README in this repository includes a broken link:

https://unpkg.com/peggy

Is this package no longer available?

**Comment by hildjj** [comment]
Willfix.  Automated version-updating code was broken.

**Comment by hildjj** [comment]
In the meantime use https://unpkg.com/browse/peggy@2.0.0/browser/build/peggy.min.js

**Comment by hildjj** [comment]
This also means that the tests that I did for 2.0.0 didn't test anything after #198.  There's now a problem with rollup, sinon, and injecting `process.env`.

So, this is a high priority, but I have to stop working for the day (holiday in the US, family stuff).  Will get back to this first thing in the morning.

**Comment by hildjj** [comment]
Blocked on #268, which should finish in a day or two.

**Comment by hildjj** [comment]
This should be fixed in v2.0.1, which just went live.  unpkg picked up the change right away, and I'm waiting for jsDelivr to see it before posting the release on GitHub.
