### ISSUE TITLE
Importing grammar rules from a file

### ISSUE THREAD

**Issue by jarble** [peggyjs/peggy#298]
I often re-use the same grammar rules in multiple grammar files, so I want to save these rules in one file and import them into other grammar files.

If I defined a rule in a file named `rules.peggy`:

`
function_call = a1:var_name "(" _ a2:exprs _ ")" {return a1+"("+a2+")";}
`

I would want to import it into another grammar file:

`
import rules.peggy
`

Does Peggy have a feature that allows grammar rules to be imported like this?

**Comment by hildjj** [comment]
We're currently talking about it [here](https://github.com/peggyjs/peggy/discussions/239), and in a draft [PR](https://github.com/peggyjs/peggy/pull/292) that isn't finished yet.

**Comment by hildjj** [comment]
Also #417

**Comment by hildjj** [comment]
I think #456 is the full fix for this.

**Comment by hildjj** [comment]
Fixed by #456
