### ISSUE TITLE
Variable names in parentheses can't be accessed

### ISSUE THREAD

**Issue by jarble** [peggyjs/peggy#306]
Whenever I try to access a variable that is defined in a named expression, the output is `undefined`:

`a = output:(a1:"parse" " " a2:"this") {return output.a1;}`

When I parse the string `"parse this"` using this grammar, the parser returns `"undefined"` instead of `"parse"`.

Is this due to a bug in the parser generator?

**Comment by hildjj** [comment]
This works as designed, for the moment  You want this:

```peg.js
a = output:(a1:"parse" " " a2:"this" { return {a1, a2}}) {return output.a1;}
```

Or:

```peg.js
a = output:(@"parse" " "this") {return output}
```

If we add #302, your code will work.

(Sorry if there are typos, I'm mobile at the moment)

**Comment by hildjj** [comment]
I'm closing this as a dup of #302.

**Comment by polkovnikov-ph** [comment]
This issue is the best evidence of how much less value there is in backwards compatibility compared to usability. Users generally expect automatic return values to work. (And I remember I was surprised it didn't too!)

**Comment by hildjj** [comment]
Let's take discussion to #302, please.  In particular, that's the place to argue for the no-`@` syntax.
