### ISSUE TITLE
Add site generator

### ISSUE THREAD

**Issue by camchenry** [peggyjs/peggy#310]
I've been using Peggy for a while now for some cool parsing stuff, and it's a really great tool. I've browsed around the GitHub issues for a while and noticed that there are many issues related to the website (which is essentially a copy of the PEG.js website). It seems like many of these issues stem from the difficulty around updating the website and maintaining it.

## Proposal

In order to make maintaining and extending the website easier: **I propose that a static site generator should generate the Peggy website.** I don't have a personal favorite, but I think any static site generator would be easier than manually modifying the HTML files directly.

## Static site generators

Like I said, I don't have a personal bias towards any of these tools particularly, but I picked a few notable ones:

- [11ty](https://www.11ty.dev/#built-with-eleventy)
  - Used by several notable developer websites: https://eslint.org, https://web.dev, https://netlify.com, https://v8.dev, etc.
- [Jekyll](https://jekyllrb.com/)
  - Used by [Ruby on Rails](https://rubyonrails.org/), [Sketch](https://sketch.com/), [Spotify for Developers](https://developer.spotify.com/), etc. 
- [Next.js](https://nextjs.org/) 
  - Used by too many sites to count
- [Gatsby](https://www.gatsbyjs.com/)
  - Used by lots of sites

## Suggestion

I have used Gatsby, Next.js, Jekyll, and Hugo for static site generation before. I have not used 11ty at all. However, based on what I have seen about 11ty, it may present the easiest migration path for the existing Peggy site, because it accepts HTML files as-is and does not rely on React/Vite/Svelte or other frameworks. This might make it easy to replace the existing site implementation without adding lots of new code.

I'd be happy to contribute a PR that adds static site generation (or at least looks into it) if that would be a helpful contribution.

**Comment by hildjj** [comment]
The direction sounds right.  Can you pick one of the above and do a *quick* prototype PR, just so we can see how it would feel to use?  Note that our current workflow is:

- Github Pages is served from the `docs` branch
- On release, `main` gets merged onto `docs`
- In the meantime, some things get cherry-picked one way or the other

**Comment by camchenry** [comment]
> The direction sounds right. Can you pick one of the above and do a _quick_ prototype PR, just so we can see how it would feel to use? Note that our current workflow is:
> 
>   * Github Pages is served from the `docs` branch
>   * On release, `main` gets merged onto `docs`
>   * In the meantime, some things get cherry-picked one way or the other

Yes, agreed! I'm going to put together a prototype _solely_ focused on adding a static site generator (no refactoring). I'll try to see if I can show how the GitHub pages workflow would work with a static site generator as well.

**Comment by polkovnikov-ph** [comment]
Oh nice! Leave some space for `/online` there, please :)

**Comment by polkovnikov-ph** [comment]
@camchenry BTW, from your Github profile it became apparent you might also be interested in [LPeg](http://www.inf.puc-rio.br/~roberto/lpeg/). It's a [eDSL](https://en.wikipedia.org/wiki/Domain-specific_language#External_and_Embedded_Domain_Specific_Languages), so the syntax is not as clean, but it's one of the most mature PEG libraries technology-wise.

**Comment by camchenry** [comment]
I opened a PR which I think will resolve this issue: https://github.com/peggyjs/peggy/pull/311. It doesn't address any issues other than adding a static site generator. But, I think this should make it easier to maintain the Peggy website and start making other changes without worrying about breaking things.
