### ISSUE TITLE
Optional line endings for `GrammarError.format`

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#320]
Also in `peg$SyntaxError.prototype.format` in generate-js.js.  We always use `"\n"` for line endings.  Although this probably *works* in modern Windows, for most cases, it's probably better to have a default second parameter for `lineEnding`.  From the CLI, we can pass in node's `os.EOL`.  We can't use `os` in the generated code, since it needs to run in the browser.

**Comment by tornikeshavishvili** [comment]
I will think about this.

**Comment by tornikeshavishvili** [comment]
I have several ideas regarding this. And i will list them all here. But first i want to ask: why is it important for peggy o run in browsers?

**Comment by tornikeshavishvili** [comment]
In comparison to server side JavaScript , in browsers JavaScript is very limited. Why not drop support for browsers? Or maybe have to versions: One with limited functionality, that will run in browsers and other for server side use, with NodeJS, where it would be possible for developers to spread their wings?

**Comment by hildjj** [comment]
`peg.js` supported many old browsers, and there are a good number of people using it there, from what I can tell.  Some of them should probably be pre-compiling their grammars, and we should probably change the docs to make that more clear. Since `peg.js` supported it, and we care about backward-compatibility, we need to support it too.  If nothing else, the online playground is a useful tool for people to learn about Peggy.

I'm open to dropping support for IE 11, which I'll probably argue for in 3.0, which will mean we will be able to modernize the browser-bound JS quite a bit.

Note that we *do* use node libraries in the CLI, where we know that the environment is going to be node.

**Comment by tornikeshavishvili** [comment]
I Agree.

**Comment by tornikeshavishvili** [comment]
CLI Parameter Sounds useful. Would it possible to determine newline character from parsed file itself?

**Comment by hildjj** [comment]
I don't think it needs to be a CLI parameter, as we can use `os.EOL` in the CLI code, and pass that into the API as needed.

Normalizing line endings is something that's straightforward to do in your own grammar, but it leads to tests failing somewhat unpredictably in the face of git's default line ending behavior.  I'm not terribly excited about doing that by default.

**Comment by tornikeshavishvili** [comment]
I Agree.

**Comment by tornikeshavishvili** [comment]
I thought regarding new line and  does not seem to be very important at this point, because existing implementation has proved itself as is.

**Comment by hildjj** [comment]
Closing for lack on interest.  Any solution would be too complex to be worth the hassle.
