### ISSUE TITLE
Unexpected behavior when transforming AST in a plugin

### ISSUE THREAD

**Issue by nene** [peggyjs/peggy#328]
I wrote a plugin to transform the AST. More specifically to add/remove some rules. So I wrote something like this:

```ts
const transformPlugin: peggy.Plugin = {
  use(config, options) {
    config.passes.transform.unshift((ast, options, session) => {
      ast.rules = ast.rules.filter((rule) => rule.name !== "unwanted_rule");
    });
  },
};
```

I was surprised to learn that my transform seemed to have no effect whatsoever. I double-checked the [documentation](https://peggyjs.org/documentation.html#plugins-api), which says:

> transform — passes that performs various optimizations. They can change the AST, add or remove nodes or their properties

I wondered, perhaps I should instead return the modified AST - but no, the types say return value is to be `void` and docs tell me to mutate the AST object. I am mutating it, but somehow my changes don't get passed to next compilation phase.

It took me a while to figure out that I'm not allowed to replace the `ast.rules` array with a new value. Instead I need to mutate the rules array in-place by pushing, popping and splicing. Something like:

```ts
const transformPlugin: peggy.Plugin = {
  use(config, options) {
    config.passes.transform.unshift((ast, options, session) => {
      const i = ast.rules.findIndex((rule) => rule.name === "unwanted_rule");
      ast.rules.splice(i, 1);
    });
  },
};
```

This code feels awkward and fragile. Years of practice have conditioned me to avoid this sort of mutations whenever possible. But now this API forces me to use this sort of style. I'll also need to add a comment to remind future me to not refactor this code into simple Array.filter().

#### Suggestions

1. Allow any sort of mutations of the `ast` parameter.
2. Better yet, allow returning the transformed version of the AST object instead of modifying it.
3. Provide a documentation example of a simple plugin that adds/removes some rules. Currently the writing of a plugin is really hard to figure out. I had to read the source code of some other plugins to figure things out.

**Comment by hildjj** [comment]
This is at least a doc bug.  I'll look into whether we can make a more substantive change.

**Comment by nene** [comment]
Thanks.

Forgot to mention, it's truly an awesome parser generator. I've been enjoin it a lot!

**Comment by hildjj** [comment]
I added a blocks-release tag but didn't actually block release 3.0.0 on this.  Looking at it for 3.0.1.

**Comment by hildjj** [comment]
I can't reproduce this at the moment.  @nene are you still seeing this?  Here is my code:

```js
"use strict";

const peggy = require("./lib/peg.js");

const transformPlugin = {
  use(config) {
    config.passes.transform.unshift(ast => {
      ast.rules = ast.rules.filter(rule => rule.name !== "unwanted_rule");
    });
  },
};

const ast = peggy.generate(`
foo = "b"
unwanted_rule = "a"
`, { plugins: [transformPlugin], output: "ast" });

console.log(ast);
```

This prints out the correctly modified AST without the unwanted_rule.  Generating source seemed to work also.

**Comment by nene** [comment]
Hmm... I'm now also unable to reproduce it.

I even checked out the original code where I experienced this problem, and I can't recreate it there. (Though I don't have the very-original code that was broken, as I never checked that in.) I suppose it was some sort of environment issue then.

I have since then written a few other plugins and haven't really experience any similar issues.

I'll close this issue and report back if I do happen to experience anything similar again.
