### ISSUE TITLE
Parser actions incorrectly(?) executed against failed matches

### ISSUE THREAD

**Issue by AndrewRayCode** [peggyjs/peggy#330]
I'm trying to write a grammar to distinguish between function declarations and function prototypes. Aka the difference between
```
float x(float arg1, float arg2);
float x(float arg1, float arg2) { ... }
```

I'm hitting an unexpected behavior in peggyjs with a grammar. It's reproducible in the online playground, by using this grammar:
```
entry = (fndef / fnproto) '.'

fndef = fnheader '){}' {
  return 'fndef';
}
fnheader = [A-Za-z_]+ '(' {
  console.log('fnheader callback hit, but not matched!');
}

fnproto = 'ab()' {
  return 'fnproto';
}
```
and this input: `ab().`

The issue, which surprised me, is that the parser action (the console.log block) is executed, even though the full production `fndef` isn't matched. 

Said another way, parser actions appear to be executed if they're inside a "parent" production, even if the parent production fails to fully consume input.

This grammar is an extreme simplification of the larger grammar I'm using that has this issue. The challenge is that function prototypes don't introduce new scopes, and function declarations do. In my own parser, and demonstrated with the above grammar, what happens is something like:
- The parser sees a function prototype lexeme, `ab()`
- The parser tries to match it against a function declaration because I've said that production should be tested first.
- The parser tries `ab` against the function header production, and matches
- The parser matches `ab` **and runs the parser action, even though the parent production hasn't completed**
- The parser then tries to match the rest of the "parent" production `{}` and fails, essentially backtracking(?) the child match
- But since the "child" function header parser action has already executed, any new state setting (in my case, creating a new scope) **does not get rolled back**

I can do some hard code reordering of the productions to surgically work around this issue, but it's pretty awkward in the grammar I'm using.

I'm not sure if this is a bug in peggy or a misconception I have. My expectation is peggy would do something like not run the parser actions until the input is known to be valid.

**Comment by Mingun** [comment]
Actions executed just after the corresponding piece of grammar are matched. Rule `fnheader` matches the input `ab()` (consumes `ab(`, leaves `)`), so the action is executed. If you want to defer execution of some actions, you should do that manually or write an extension to generate such parser for you. See https://github.com/pegjs/pegjs/issues/214.

In your case it seems you just use the incorrect action to start a new scope. If scope is started after parsing function declaration, then why you try start it after parsing a function header (i.e. before the function declaration is parsed)? Move scope creation to the `fnproto` rule.
