### ISSUE TITLE
Look-ahead

### ISSUE THREAD

**Issue by moar55** [peggyjs/peggy#331]
How many look-ahead symbols does peggy's parser look for? Would it be possible to extend it to more symbols, and would it give me a real speedup (with a memory drawback ofc)?

**Comment by Mingun** [comment]
Infinity. That is a theoretical maximum, the real grammars of course can have some concrete limits (for example, a grammar `start = 'a' / 'b'` has an obvious limit of 1 symbol). Writing a pass that would calculate lookahead min/max is an interesting challenge, that could be used in some optimizations!

**Comment by hildjj** [comment]
Closing, because it's been answered.  Please reopen if you need more help.
