### ISSUE TITLE
docs not building on stable

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#342]
@camchenry I need help please.

See https://github.com/peggyjs/peggy/actions/runs/4244431952 for the latest failure.

**Comment by hildjj** [comment]
OK, I just did that, and it succeeded, but it doesn't look like anything got published?

**Comment by hildjj** [comment]
Oh, there were extra steps in the release instructions that I didn't follow because I didn't quite understand them. :(

- [ ] (For version 2.1) remove docs branch, create new orphan docs branch, git rm -rf . in docs branch. Push to upstream
- [ ] Run docs workflow
- [ ] (For version 2.1) re-point GH Pages from stable/docs to docs/

Do those still look right?

**Comment by camchenry** [comment]
Yeah, that seems right to me. It looks like the first two steps are done, since the docs branch contains only the files we need to deploy. This is what my settings looks like in the fork I have:

![image](https://user-images.githubusercontent.com/1514176/220687074-5f353ea8-961e-448f-808d-807fccd7f81f.png)

**Comment by camchenry** [comment]
Sorry I should add that you can find this in the repository settings, under the "Pages" section.

**Comment by hildjj** [comment]
I deleted the old docs branch, then did `git checkout --orphan docs` locally.  Cleaned that directory up.  Now I'm trying to push it, and I'm getting:

```
$ git push upstream docs
error: src refspec docs does not match any
error: failed to push some refs to 'https://github.com/peggyjs/peggy.git'
```

Is that because there aren't any files to push?

**Comment by hildjj** [comment]
Woot.  That fixed it.  Thanks for the hand holding.
