### ISSUE TITLE
Peggy can't parse superfluous semicolons

### ISSUE THREAD

**Issue by gamesaucer** [peggyjs/peggy#346]
**_Steps to reproduce:_** Parse the following grammar:
```pegjs
Start = Part*; ;
Part = .
```

**_Expected result:_** It is a valid Peggy grammar, since the separation of its rules is not ambiguous.
**_Actual result:_** It is not a valid Peggy grammar.

This happens because Peggy does not accept duplicated semicolons. I suppose not fixing this could be justified with the reasoning that duplicated semicolons are almost certainly a mistake on the part of the programmer, but I wanted to at least point out this limitation.

**Comment by hildjj** [comment]
This one I might be open to changing.  However, I want to make sure I can capture the extra semis in peggy-eslint-parser first.  Will leave this open to discussion.

**Comment by hildjj** [comment]
After looking at peggy-eslint-parser, this is still an easy fix.  Including in v3.0.1.

**Comment by polkovnikov-ph** [comment]
Thanks for pointing this out!
