### ISSUE TITLE
The `$` prefix is ambiguous

### ISSUE THREAD

**Issue by gamesaucer** [peggyjs/peggy#347]
**_Steps to reproduce:_** Parse the following grammar:
```pegjs
$Start = $Part
$Part = .
```

**_Expected result:_** The validity of this Peggy grammar is decided by whether rule names can start with `$`.
**_Actual result:_** It is not a valid Peggy grammar because rule `Part` is not defined.

Because Peggy allows the dollar sign `$` to start rule names AND has a `$` prefix operator, one of the following must be true:

1. The first `$` is always parsed as an operator. In this case, a rule cannot reliably be matched simply by writing its name. There is also no way to match `$Part` without returning the text rather than the match. This is the current implementation.
2. The first `$` is always parsed as part of the identifier. In this case, to return the matched text of a nonterminal, a space is required before the nonterminal to disambiguate between `$ Part` (return text of rule `Part`) and `$Part` (return match of rule `$Part`), or the expression needs to be wrapped in parentheses. This makes it inconsistent with the operator's behaviour before terminals.
3. The `$` is parsed as part of the identifier if that identifier exists. In this case, adding a rule called `Part` would break existing references to a rule called `$Part` or vice versa. It would also it becomes ambiguous what a `$` does before a nonterminal and require an extra parsing pass to determine how it is interpreted.

All those options seem undesirable to me. Instead, I'd advocate for either disallowing `$` at the start of rule names, or changing the `$` operator to something that cannot appear at the start of an identifier. Unfortunately, any alteration to this behaviour would be a breaking change. So if it's decided this won't be fixed, I understand why that's the case.

**Comment by hildjj** [comment]
This is a valid issue, and I'm surprised it hasn't come up before.  I don't have a better solution that disallowing `$` as a start character in identifiers.

@Mingun any insights?

**Comment by Mingun** [comment]
Yes, I think we should forbid that symbol in identifiers (only at start or everywhere if `something$something` could be treated ambiguously). It's amazing how it hasn't been noticed before

**Comment by hildjj** [comment]
I think `$` is fine in the middle of identifier.

```peg.js
top = fb

fb = $foo$bar

foo$bar = foo $bar

$foo$bar = 'baz'

foo = 'foo'

bar = 'b' 'a'+ 'r'
```

this matches "foobaaar", but not "baz".
