### ISSUE TITLE
bug in repetitions

### ISSUE THREAD

**Issue by RubenArtmann** [peggyjs/peggy#364]
grammar:
```pegjs
test = test:"a" "b" ("c" &{return test==="a" || error(`test = ${test}`);})|1..," "|
```
example:
```
abc c
```
resulting error: `Line 1, column 6: test = b`
even though the label `test` only gets set to `a` at the beginning

i have tried looking at the generated code:
it seems like you unwrap the loop into something like `"c" {...} (" " "c" {...})*`
but the second version looks for `test` in the wrong place (one higher in your stack??)

-----------

for now i can use this hack: 
```pegjs
test = test:"a" ("" {return test;}) "b" ("c" &{return test==="a" || error(`test = ${test}`);})|1..," "|
```
but i shouldn't have to do that.

**Comment by hildjj** [comment]
@Mingun yes, this looks like a codegen bug.

**Comment by Mingun** [comment]
Yes, I already found and fixed bug, I'll add few tests and prepare a PR in neartime.
