### ISSUE TITLE
Uncaught error thrown if rule is missing

### ISSUE THREAD

**Issue by mojavelinux** [peggyjs/peggy#374]
When generating a parser from a grammar file using the `peggy` CLI from 3.0.1, the command throws an uncaught error if a rule is missing:

```
Uncaught Error
 TypeError: Cannot read properties of null (reading 'split')
    at /tmp/peggy-test/node_modules/peggy/lib/grammar-error.js:88:18
    at Array.map (<anonymous>)
    at GrammarError.format (/tmp/peggy-test/node_modules/peggy/lib/grammar-error.js:86:30)
    at PeggyCLI.error (/tmp/peggy-test/node_modules/peggy/bin/peggy-cli.js:372:45)
    at PeggyCLI.main (/tmp/peggy-test/node_modules/peggy/bin/peggy-cli.js:659:12)
```

Here's the command I'm using:

```
$ peggy -o test-parser.js test.pegjs
```

This seems to happen because the `GrammarError` class assumes that the associated sources are non-null. On line 88, if I replace:

```js
text.split(/\r\n|\n|\r/g),
```

with

```js
text?.split(/\r\n|\n|\r/g),
```

then I'm able to see the actual error being thrown:

```
Error parsing grammar
error: Rule "line" is not defined
 --> test.pegjs:1:8
  |
1 | root = line eof
  |        ^^^^
```

If I print the sources inside the problematic function, I see the following:

```
[
  { source: 'test.pegjs', text: 'root = line eof\n\neof = !.\n' },
  { source: null, text: null }
]
```

As far as I can tell, the second entry is the test grammar source, which is supposedly optional. I can reproduce this if I don't specify test input at all or if I specify test input using a file (`-T`).

**Comment by hildjj** [comment]
Do you have a small grammar that can reproduce this?  It'll make it easier to write a test.

**Comment by mojavelinux** [comment]
Sure thing. The grammar is actually in the error message, but I'll write it out to make it easier to copy:

```
root = line eof
eof = !.
```

**Comment by hildjj** [comment]
OK, this is a real issue, but it's in peggy-cli.  I will probably also do the null check, but it should be more like an assertion because it's an indication of a programming error somewhere else.

**Comment by mojavelinux** [comment]
For reference, I observed that it is possible to suppress this condition by adding the `-t ''` CLI flag. That seems like a good workaround until a fix is available.
