### ISSUE TITLE
Refer to specific grammar rule

### ISSUE THREAD

**Issue by barsdeveloper** [peggyjs/peggy#386]
Is it possible to have one single grammar and decide to parse a specific text using one rule of this grammar which is not the main one?

Let's say I have the following, very simple grammar, boolean is my start rule.
```pegjs
false = "false" { return false; }
true  = "true"  { return true; }
boolean = true / false
```
But sometimes I would like to access in the generated file, no only boolean but maybe I just need to parse false or true, is that possible? I mean to export them separately through cli.

**Comment by Mingun** [comment]
Yes, see the `--allowed-start-rules` CLI argument / `allowedStartRules` config / API parameter:
```
$ node .\bin\peggy.js --help
Usage: peggy [options] [input_file]

Arguments:
  input_file                       Grammar file to read.  Use "-" to read stdin. (default: "-")

Options:
  ...
  --allowed-start-rules <rules>    Comma-separated list of rules the generated parser will be allowed to start parsing from.  (Can be specified multiple times) (default: the first rule in the grammar)
  ...
```

**Comment by hildjj** [comment]
Also of note: you can specify `"*"` for the allowed start rules, to allow any rule to be a starter.

I'm going to keep this open in order to make sure the CLI docs say that.

**Comment by barsdeveloper** [comment]
Maybe is my luck of understanding the output but as I see it, it only exports one function called parse. How can I access some peg$parsetrue? Just to clarify, what I mean is not for the grammar to parse either true or false, I want to precisely pick the rule that parses true and failes with false.

**Comment by hildjj** [comment]
```js
"use strict";

const peggy = require("./");

const  { parse } = peggy.generate(`
false = "false" { return false; }
true  = "true"  { return true; }
boolean = true / false`, {
  allowedStartRules: ["*"],
});

console.log(parse("true", { startRule: "boolean" }));
```

**Comment by barsdeveloper** [comment]
Understood, this is basically the equivalent of the CLI but when generating the grammar at runtime. I hoped there was some way to flag rules in the grammar itself to tell the generator (CLI or peggy.generate) what default starting rules to have.

Let's say I have mygrammar.peggy
```pegjs
*false = "false" { return false; }
true  = "true"  { return true; }
*boolean = true / false
```
And I want the starting rule to be either boolean or false. But as I understand this is not currently supported.

**Comment by hildjj** [comment]
You are correct there is currently no mechanism inside the grammar for this, although that's a good idea.  When we do rule importing (see #292 for initial work), some rules might be marked as public and others as private, for instance.  There are other bits of metadata that might be interesting about rules, such as anticipated types for Typescript output, enabling tracing per-rule, example inputs that get automatically tested, etc.

We could come up with something like ECMAscript/Typescript decorators, have a syntax for comments like JSdoc, or decide that all of this is too complicated for the benefits that might accrue.

In the meantime, just keep an array of the rules you want to be made visible whenver you would have generated a `*` prefix, and pass that in where the `['*']` is in my example.
