### ISSUE TITLE
[docs] Parens create a pluck context

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#398]
It's not clear from the docs that this is legal:

```peg.js
foo = "a" b:(@"c" "d") { return 2 }
```

because the parens create a new context for returns.  Same with the old way:

```peg.js
foo = "a" b:(first:"c" "d" { return first })
```

**Comment by hildjj** [comment]
Parens also create a `location()` context.

**Comment by hildjj** [comment]
I figured I'd fix 398 while I was in there.

**Comment by polkovnikov-ph** [comment]
Oh, BTW, do you remember when it was introduced? I remember at least old versions of PEG.js didn't have this kind of scoping.

**Comment by hildjj** [comment]
It was 1.1: https://github.com/peggyjs/peggy/blob/dfca04cf000d9be3d8f4a99314ccbedef744db33/CHANGELOG.md?plain=1#L371

**Comment by polkovnikov-ph** [comment]
Thanks!

It was one of the larger improvements to DX, but I didn't know it happened after the fork.

**Comment by hildjj** [comment]
It was technically after the fork, because we forked from the last-known-good spot, then the plucks were back-ported from head -- because that was the feature I wanted to be released enough to want the fork. :)
