### ISSUE TITLE
doc example doesn't correspond to code example

### ISSUE THREAD

**Issue by yukulele** [peggyjs/peggy#405]
this error is very confusing when trying to read the documentation:

https://github.com/peggyjs/peggy/blob/dfca04cf000d9be3d8f4a99314ccbedef744db33/docs/documentation.html#L1072
https://github.com/peggyjs/peggy/blob/dfca04cf000d9be3d8f4a99314ccbedef744db33/docs/js/examples.peggy#L35

**Comment by hildjj** [comment]
Agree there's something going on there.

**Comment by yukulele** [comment]
Thanks!

And sorry but I realize that there is still a small error,

The input have the wrong value:

https://github.com/peggyjs/peggy/blob/ef06447afae3d1ff37a043a95045b31b14c66465/docs/documentation.html#L1101
```suggestion
       <input type="text" value="aaa   bb" class="exampleInput" name="pluck_1">
```

**Comment by hildjj** [comment]
drat, thought I caught that.
