### ISSUE TITLE
Playground syntax highlight grammar breaks when using template literals

### ISSUE THREAD

**Issue by KrofDrakula** [peggyjs/peggy#423]
Was playing around with the online playground and noticed that template strings break highlighting when using interpolation:

<img width="1680" alt="image" src="https://github.com/peggyjs/peggy/assets/112161/f8817898-3f9a-442d-82c9-571c07d92f9a">

The file still parses correctly but the highlighting is broken from that point onwards.

**Comment by hildjj** [comment]
Good catch.  I'm going to mark this one as "help wanted", and see if someone who knows how the highlighting works can send a PR.

**Comment by KrofDrakula** [comment]
Might be related to #296.

**Comment by reverofevil** [comment]
Yeah, it's been a problem of CodeMirror's JS grammar for ages. Really should switch from CM to something else.

**Comment by hildjj** [comment]
Let's talk about options on #426.  I agree that's the correct, lowest-effort approach to solving this.

Going to close this as a dup.
