### ISSUE TITLE
Documentation misleadings

### ISSUE THREAD

**Issue by Bot12313** [peggyjs/peggy#450]
## Problem
Some examples in the [documentation](https://peggyjs.org/documentation.html) seems either outdated, incorrect, or impossible to reproduce in online version on Peggy.  
  
## & { predicate }
The example appears to be working fine but is impossible to reproduce the results in the online version. 
  
<img src="https://github.com/peggyjs/peggy/assets/25652956/f30d90ba-b2a1-4948-b588-a28fd212f6a1" width=600/>  
<img src="https://github.com/peggyjs/peggy/assets/25652956/2cd8b98d-24e3-45af-9d36-701c73d1d3c4" width=600/>  
  
Even after adding the "match" label, it still produces error.
  
<img src="https://github.com/peggyjs/peggy/assets/25652956/8f967ed0-0606-4d2c-8464-cca94d0b5bd8" width=600/>    
  
## @ ( label : )? expression
Unable to use the "matches" examples noted below.
  
<img src="https://github.com/peggyjs/peggy/assets/25652956/14f53430-d4cf-416a-9d41-bdccf2c84b27" width=600/>

**Comment by Bot12313** [comment]
## & { predicate }
It appears that everything is now being returned as a list, so it needs to be converted back into a string to work with it.

<img src="https://github.com/peggyjs/peggy/assets/25652956/989e7f13-4c56-4ddf-8c65-f844469996b8" width=600/>

**Comment by hildjj** [comment]
The posPredicate one should read:

```peg.js
posPredicate = @match:$[0-9]+ &{return parseInt(match, 10) < 100}
```

note the `$`.  This returns "23" but fails on "233".  The `@` is so that the predicate doesn't return a confusing null.

The second one needs a better default input of "aaa  bbbb" or something.

Valid issue, willfix.
