### ISSUE TITLE
VERSION not in peg.d.ts

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#47]
Won't block release for this.  Next time someone is in the file, please fix.

**Comment by phpnode** [comment]
not sure I understand, what's missing here?

**Comment by hildjj** [comment]
```js
require('peggy') // ->
{
  VERSION: '0.11.0',
  ...
```

**Comment by hildjj** [comment]
Oh crap.  That VERSION is maintained by hand, which is why it's wrong.  I'll go fix that, but leave this bug for updating the .d.ts
