### ISSUE TITLE
Format bare gives no error when trying to import another parser

### ISSUE THREAD

**Issue by XenoS-ITA** [peggyjs/peggy#490]
When trying to compile a file with peggy if you set the format to bare the import is simply ignored with no warning indicating that bare cannot import

Step to reproduce:
- Create a paggy file that imports another file
- Compile the following file using bare (`npx peggy path/to/file.peggy --format bare`)
- The compiled file will not have imports but paggy will not warn you

What should come out:
An error or warning that the import was ignored.
Maybe for the api change the default format to `commonjs` or throw an error

**Comment by XenoS-ITA** [comment]
you are totally right, it could be done with the next big version also because the fact that the CLI has `commonjs` as default and the API as `bare` does not makes not too much logical sense (in my opinion)

**Comment by hildjj** [comment]
Let's fix this, and we can then open another issue to revisit the default at the next breaking change.

**Comment by hildjj** [comment]
I'm not going to cut a release just for this, since there is a work-around.
