### ISSUE TITLE
Allow use of an empty array as default value in allowedStartRules option

### ISSUE THREAD

**Issue by XenoS-ITA** [peggyjs/peggy#493]
### How the feature should work
When an `empty` or `null array` is passed peggy should take the default value, which is the first rule.
Right now if you define allowedStartRules there is no method to use the first rule.

### Use case behind it
In the following code, if the file is a library, [all rules should be added as start](https://peggyjs.org/documentation.html#importing-external-rules) instead if it is not the first rule should be taken 
```js
const output = peggy.generate(fileContent, {
    format: "commonjs", 
    output: "source", 
    allowedStartRules: isLibrary ? ["*"] : []
})
```

> Even some kind of ENUM might be fine

**Comment by hildjj** [comment]
I'm making it so that `null`, `undefined`, and `[]` all get the default start rule.
