### ISSUE TITLE
4.0.1 dropped support for Node 18

### ISSUE THREAD

**Issue by caugner** [peggyjs/peggy#495]
`peggy` itself requires Node `>=18`, but 4.0.1 added a dependency on `@peggyjs/from-mem` in https://github.com/peggyjs/peggy/pull/480, which requires Node `>=20.8`, effectively introducing a breaking change.

**Comment by hildjj** [comment]
Nod, will fix.  Parts of from-mem require 20.8, but not all of it.  It does a runtime check and throws an error, so I think it's safe to change the min version on from-mem back to 18.

**Comment by hildjj** [comment]
See https://github.com/peggyjs/from-mem/pull/8

**Comment by hildjj** [comment]
Fixed in 4.0.2
