### ISSUE TITLE
Start and end index of matched rule in the source code.

### ISSUE THREAD

**Issue by alex-klimov** [peggyjs/peggy#503]
I need to provide additional information in the editor, when user stands on the text matching particular rules.

Is there built-in way to return start and end index of the text matched with a rule?

**Comment by Mingun** [comment]
Yes, [`location()` or `range()`](https://peggyjs.org/documentation.html#locations). Try to see this output:
```pegjs
start = "a" { return {
  offset: offset(),
  text: text(),
  range: range(),
  location: location(),
}; }
```

**Comment by alex-klimov** [comment]
Thanks, this works brilliantly!

One quick question before closing the issue: `range()` seems to give exactly what I was asking for. In addition, it has property `source` which is `undefined`. Is this supposed to be exactly as what `text()` returns? Should I be concerned that `range.source` is `undefined`?

**Comment by Mingun** [comment]
Just read the linked documentation. This is the value of `options.grammarSource` and it is intended to give location a filename.

**Comment by alex-klimov** [comment]
Found it, thanks! Linking it here, so other people might make use of it in the future:
https://peggyjs.org/documentation.html#locations

**Comment by hildjj** [comment]
One additional quick note.  I sometimes use a function called "loc" when I'm applying locations to lots of AST nodes:

```js
{
  function loc(node) {
    node.loc = location();
  }
}

foo = "foo" { return loc({type: "foo"}); }
```

`location()` knows about the current parse state, and the function is available within scope to all initializer functions inside of the initial {} (but NOT top-level initializers using {{}}).  I particularly use this approach when I have to modify the location to be in a different form for a specific AST, like here in [@peggyjs/eslint-parser](https://github.com/peggyjs/peggyjs-eslint-parser/blob/17c1b61d3217179777a1189b79e2768c0a4f413c/src/parser.peggy#L58)
