### ISSUE TITLE
Infinite repetition in RFCs

### ISSUE THREAD

**Issue by zp-zpanda** [peggyjs/peggy#516]
Some RFCs such as RFC 5322 (Internet Message Format) allow infinite repetition in their ABNF:

```
(RFC 5322 3.2.5 Miscellaneous Tokens)
...
unstructured    =   (*([FWS] VCHAR) *WSP) / obs-unstruct
...

(RFC 5322 4.1 Miscellaneous Obsolete Tokens)
obs-unstruct    =   *((*LF *CR *(obs-utext *LF *CR)) / FWS)
...

(And many more)

```
I have tried using [node-abnf](https://github.com/hildjj/node-abnf) to generate a full Peggy tree from the ABNF, but of course Peggy errors. Is there any method to mitigate that?

Related: #357, #367

**Comment by hildjj** [comment]
First, see errata [1905](https://www.rfc-editor.org/errata/eid1905).  Making that change in the ABNF yields a Peggy grammar that compiles.

Then, check the other [errata](https://www.rfc-editor.org/errata/rfc5322) for a few more grammar changes.

In general, these sorts of errors often mean there's something wrong with the starting assumptions, so there isn't a mechanical fix for them.

**Comment by zp-zpanda** [comment]
I see... I will try again after incorporating those errata. Thank you so much!

**Comment by hildjj** [comment]
I'm closing this, but please re-open it if you still have trouble.
