### ISSUE TITLE
Grammar with token "constructor" fails to generate

### ISSUE THREAD

**Issue by PaulGVernon** [peggyjs/peggy#520]
I noticed that the following grammar 

```
a = "constructor"
```

fails in version 4.0.2 with

```
error parsing grammar
Cannot read properties of undefined (reading 'length')
```

This was not the case in version 3.0.2

**Comment by hildjj** [comment]
Validated, and I see where the problem is.  Investigating solutions.

**Comment by hildjj** [comment]
I'll do a release later today, after fixing #513 and #522.
