### ISSUE TITLE
There's a lot of wasted space.  Could I remove it?

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#65]
`pegjs` has enormous boatloads of whitespace emitted that doesn't need to be, in the "for speed" version

the "for speed" version should be renamed to "for human readability," and a new version should be emitted "for speed" which is the current one with all the unnecessary whitespace removed, and be the new default

the speed impacts of unrolling are sometimes lost by the download slowdown

on larger parsers it's sometimes 80% of the file

**Comment by hildjj** [comment]
Let's wait for after #60 to land.  I'm currently only including a webpack minimized output, and it's radically smaller than before.  I'll also probably generate one with a sourcemap inside, at which point yeah, removing the extra useless whitespace will be welcome.

Keeping this open to revisit later.

**Comment by StoneCypher** [comment]
> I'm currently only including a webpack minimized output, and it's radically smaller than before.

FYI, `rollup` is reliably 10+% smaller still.  I'd be happy to convert it for you when it comes time, if you like.

&nbsp;

> also probably generate one with a sourcemap inside

My opinion is that a sourcemap as a second file is superior because then most clients won't spend bandwidth loading it and you don't need a second copy of the deliverable, but as you prefer

If you are open to second copies, the traditional second copy is an unminified human-readable version, so that someone developing from CDN can temporarily switch to that to debug, then back

**Comment by StoneCypher** [comment]
> Let's wait for after #60 to land.

As you see fit, but they're 100% unrelated.  This is just about `peg`'s string output

**Comment by hildjj** [comment]
I'm happy to take a webpack->rollup patch once I get something working.  I haven't had enough rollup success in the past, but that's because I haven't tried hard enough.  I'll be open to almost all combinations of minified/sourcemap'd/etc as long as there's one super-small UMD amongst the choices.

Re: waiting on #60, it's mostly I don't want to deal with the merge until after that; everything is moving around.

**Comment by StoneCypher** [comment]
> I'm happy to take a webpack->rollup patch once I get something working

Awesome 😁 

&nbsp;

> I haven't had enough rollup success in the past, but that's because I haven't tried hard enough.

I will be the first to admit that it's a hard initial hump to get over.

My strongly held belief is that it's worth it.

**Comment by hildjj** [comment]
Will prettier mess with whitespace?  If so, this is related to #42

**Comment by StoneCypher** [comment]
This bug does not regard the formatting of `peg`, but rather, the formatting that `peg` creates in its generated files.

`prettier` will not impact this (unless it's run against the output and please god no)

**Comment by StoneCypher** [comment]
although actually now that i think about it

prettier just sort of arbitrarily rewrites string constants and, for unrelated reasons, it's almost certain to cause completely unnecessary trash fires all over the place
