### ISSUE TITLE
Higher unicode

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#67]
There's a long argument to be had here.  It's been had several times.

One of the big problems with Javascript is that it actually mandates 16-bit max character storage.  (lol what?)  It does *not* mandate representation, but pretty much everybody is utf16le as a result.

This won't last forever.  There's no good backcompat reason not to switch; the space outside the BMP is becoming increasingly important; et cetera.

There exists a patch for [astral codepoints](https://github.com/pegjs/pegjs/pull/651) and a patch for [uppercase supers](https://github.com/pegjs/pegjs/pull/616).

There exist arguments against; some people feel that differing from contemporary Javascript is bad.  However, this is almost certainly going into future Javascript, and this is an important topic now for many of us (dealing with surrogate pairs in PEG is nigh impossible.)

I believe that one or both (ideally at least the first) should go in.

**Comment by hildjj** [comment]
See https://github.com/peggyjs/peggy/discussions/15 please, and copy from this whatever needs to be in that discussion.  Let's discuss there, then open a bug once we have a plan of attack.
