### ISSUE TITLE
When peg generators are in modules, use shorter names

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#68]
Right now, peg generates methods `peg$foo` for methods properly named foo as a faked namespace

This doesn't minify well and wastes tremendous space when the parser is already isolated by other means, such as an iife, an es6 module, et cetera

This should be made dynamic

**Comment by hildjj** [comment]
As long as we can ensure that user-specified names don't interfere with names in our own namespace.  There are several ways of doing that, if it isn't being done already.

**Comment by StoneCypher** [comment]
Yeah.  Besides, there's two kinds of collision: internal and external

An external collision would be if `peg` generated a parse function `foo` and that was allowed to collide with a function in the host context called `foo`

An internal collision would be if the user of `peg` created a rule with the same name as one of peg's internal mechanisms

So there's a whole *lot* of ways to do this, right?  But generally speaking, those two (es6 modules and iifes) are enough for every situation that I can think of for external.

If we just say "if it's something that has modules, eg es6/ts, stuff it in a module; otherwise in an iife" I think we're done, and we get a big ol' size win out of it

All we really need then is to keep track of name collisions, and pre-load names we need to protect, for internal collisions

Pretty much the same thing a minifier does
