### ISSUE TITLE
Move as much of the parser to library methods as possible, for testing's sake

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#69]
This is really just moving things across an ABI, but it's a little defect prone initially

This shouldn't be done until rollup is in place, as cross-boundary calls in webpack are both space and time expensive

**Comment by hildjj** [comment]
check out how I'm referring to them in the monorepo branch.  Since `peggy` is a real module there, the require syntax is a lot cleaner.

**Comment by hildjj** [comment]
We may also be talking about different things.  I was referring to things like https://github.com/hildjj/peggy/blob/4d0767ff7895e61d54fa04f6fdcd94fb5f94c8b9/pkg/test/lib/unit/compiler/passes/generate-bytecode.spec.js#L5
