### ISSUE TITLE
Generated code has wrong version number

### ISSUE THREAD

**Issue by GreenImp** [peggyjs/peggy#72]
I have noticed that the Peggy version number in the generated output is incorrect. It says;

```javascript
// Generated by Peggy 0.11.0.
//
// https://github.com/peggyjs/peggy
```

Whereas I presume it should be:

```javascript
// Generated by Peggy 1.0.0
//
// https://github.com/peggyjs/peggy
```

**Comment by hildjj** [comment]
Good catch.  This is fixed in the monorepo branch, which will drop as soon as i've got reviews.

**Comment by hildjj** [comment]
Since it doesn't look like we're going to merge the monorepo patch, I created a separate PR to fix this.
