### ISSUE TITLE
Post-monorepo commentary: CI builds should be matrix builds

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#75]
After [the monorepo](https://github.com/peggyjs/peggy/pull/70/files#diff-014228303dff9a1af15f4bbd18401f906380129b10ae2a2c62f8b8be592ff88eR38) drops, the CI yaml should generate a matrix build at least across [`operating systems`, `node versions`].

I am happy to do the labor.  This should not block the current PR.

**Comment by hildjj** [comment]
Nod.  Windows is probably most important to add, but I'm afraid the parts of the system that are most OS sensitive are in the build and release pipeline, which will be hard to reach.

**Comment by StoneCypher** [comment]
I already did it for my now-dead fork.  It'll be really hard in `mocha`, but I'm in the middle of advocating for `jest`, which I'm willing to do the labor for, and under that context it's actually not too bad

**Comment by hildjj** [comment]
I'm ok with the jest PR coming first.
