### ISSUE TITLE
Post-monorepo commentary: Please consider not-mocha

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#76]
`mocha` is mostly dead, and its coverage analysis is badly broken, as it's based on a heavily outdated version of `istanbul` which is patched to sorta-es6.

The `istanbul` people gave up and started over, creating `nyc`.  Using a non-`nyc` based test engine on es6 is dangerous if you think coverage is important.  (I think coverage is important.)

I recommend that we consider moving to `jest`.  I am willing to do the labor, and [I have done this on much larger test sets for my own projects recently](https://github.com/StoneCypher/jssm/pull/417), without codemods (ew,) so I'm not going in blind of what I'm offering.

**Comment by hildjj** [comment]
There's also c8 to consider. I'm no mocha fan.  Let's start a discussion on which framework to use.
