### ISSUE TITLE
Remove custom benchmarking util in favor of standard one

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#79]
wrt https://github.com/peggyjs/peggy/pull/70/files#diff-373018ba4534661dac9c14da96561406479fbdfadef98eed966f9697372eb469R40

We shouldn't have our own benchmarking utility.  It's nonsense for us to maintain this code.  These didn't exist when David wrote this, but now they do, and the common ones these days have a better understanding of statistical significance and so on

**Comment by hildjj** [comment]
See https://github.com/peggyjs/peggy/discussions/64

**Comment by StoneCypher** [comment]
Aha
