### ISSUE TITLE
Eventually we should just use some or another CLI lib

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#80]
wrt https://github.com/peggyjs/peggy/pull/70/files#diff-373018ba4534661dac9c14da96561406479fbdfadef98eed966f9697372eb469R104

... ew

Everybody argues about what CLI to use.  I kind of like `commander` but I'm open to most things

Whatever it is should build cleanly under `rollup` on all three major platforms, bare minimum

**Comment by hildjj** [comment]
See https://github.com/peggyjs/peggy/discussions/31

**Comment by StoneCypher** [comment]
oh
