### ISSUE TITLE
Bytecode tests should use constants, rather than magic numbers

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#81]
https://github.com/hildjj/peggy/blob/4d0767ff7895e61d54fa04f6fdcd94fb5f94c8b9/pkg/test/lib/unit/compiler/passes/generate-bytecode.spec.js#L5

I assume that [these are probably they](https://github.com/peggyjs/peggy/blob/main/lib/compiler/opcodes.js)

**Comment by Mingun** [comment]
Probably, just comments with bytecode names will be enough (as I did in all my syntax extensions in my fork).

Your assumption about bytecode source is right.

**Comment by StoneCypher** [comment]
Well, you're much deeper about this tooling than I am

If you think so, maybe you're right

I'll leave it open for a day in case anyone else has an opinion, and if not, I'll close it and cede to yours
