### ISSUE TITLE
you asked me to comment on tools/release

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#91]
[you had asked me to comment on tools/release](https://github.com/peggyjs/peggy/issues/86#issuecomment-822983640)

https://github.com/peggyjs/peggy/blob/main/tools/release#L90

there's a lot of value in doing things in the standard way.  i worry that i'm becoming a wet blanket about this

this has no attachment to pipes.  everything is run through a large monolithic custom script.

there's no way to multiplex processes here.  you can't see what actually went wrong in an action.

because this is all buried in a custom script, we lose all piping benefits of the unix way, and gh actions' reporting stuff is no longer available

we can't re-use any standard actions because there's no way to put anything in the positioning chain

users can't use individual steps at their discretion; there can only be one path through this, ever

we're trying to manually implement publishing through npm through a wrapper script in a javascript.  ***this is extremely dangerous and is likely to get hacked.***

we're writing our own child process spawning and queueing system

i don't understand why we keep inventing unnecessary infrastructure

there's something really good here for this already.  it's called `npm scripts`.  it has the unix interface, which carefully correctly manages process parallelism (this is hard) and has standard logging expectations.

everybody already knows how to use it and work with it.

the result to replace this code is seven lines and is in a standard place where every node programmer will immediately look for it, is robust to several classes of operating system problem that are not handled here,  and have been extensively tested

we don't want to write our own auto-publish.  that's dangerous.  if we're going to auto-publish, it should be the standard one that's been gone over extensively for security topics.  

it would be difficult to use that here because it's an action and this doesn't participate in the pipeline lifecycle

this also appears to be doing git diffing.  why?  is the idea that this would be automated on the developer's local machine?  that's not reproducible.  this needs to be in ci/cd, and if it's in ci/cd, that's already done

i'm currently somewhat confused what this file is for.  it was represented as equivalent to a two line script i put up that replaces a file with a number exported, and allows the source code compile process to handle everything else

these are actually quite night and day different

**Comment by hildjj** [comment]
I'm willing to take a patch to replace this, but I want to make sure the functionality remains.  What I'm trying to accomplish is ensuring that a release gets done in completely automated fashion, including several ways I've messed up builds in the past.  The `git diff` bits are trying to ensure that the repo is all checked in clean at each step.  The auto-publish doesn't happen for me because there's a pause for OTP.  I'm planning on making 2FA required in the npm config, once @phpnode turns it on for his account.

> i don't understand why we keep inventing unnecessary infrastructure

Would you mind please assuming that there are reasons I'm doing some of these things that are not *just* because I'm stupid?  It will make it easier for us to make progress more quickly.  There are definitely things I'm going to learn from this process, and I'm willing to learn those things and make changes.

**Comment by StoneCypher** [comment]
it needs to be possible to say "this is dangerous" without getting yelled at for it

**Comment by StoneCypher** [comment]
> What I'm trying to accomplish is ensuring that a release gets done in completely automated fashion, including several ways I've messed up builds in the past.

i'd like to help, but the tone of this last comment is very difficult for me

i've said the same things i said in this comment for about five years now, since long before you showed up.

i said them to you in a friendly way a week ago, and then again two days ago.

i showed you working code and an example.  i emphasized how important it was that it was two lines, and that it was separated into its own script, so that it followed the unix way.

you told me "oh yeah that's totally what we're doing" and asked me to come look at this.

.

i'm having some trouble with communication.  when i asked you to please not install lerna, pointed out that this had already been done to this repo several times with disastrous consequences, then pointed out the universal normalcy of those consequences, you said there were no new package managers going in.  then it was both lerna and pnpm.

then it was a fight to get this project not put into a position where it would lose 40% of its historical contributions, and exclude me.

next when i said "please don't make a monolithic script build, let's do this in the standard way in scripts and use the standard github actions," you said that sounded good.  but then you posted a really massively overengineered third party solution.  i said "no, we can just do it like this," and tried to show you one.

i don't know if i think you read it?

you told me to come here and comment.  so i did, and you said i was calling you stupid.

i'm not, though.  actually, in my head, quite the opposite.  i believe that only smart people over-engineer, because i believe that stupid people who try to eat the ground early, and learn not to do this.

it makes me sad, because i didn't actually throw any insults.

i just said the same thing i keep saying: "hey guys, can we please do it the standard way that i told you about before this went in?  i already have it done, i can just donate it."

and then i see something, and i try it, and it excludes me as a developer.  this is #3 in a row.  this time it's because there's an unknown script invoking child process, so both my work and my home antivirus panic.  i can tell norton to shut up, but not my work antivirus.

&nbsp;

i want to help, because this tool is incredibly important to me.

can you please tell me what was wrong with the way i communicated specific engineering concerns to you, that you ignored all of them?

can you help me understand how you would like me to communicate, in the future, my confusion?  

is there actually something wrong with my saying "here is a practice which is repeating that i do not understand?"  at literally every job i've ever had, that would have been treated as a valuable concern.

i don't want to feel like a bully.  i haven't criticized you in any way.  i most certainly did not call you stupid, and thought the opposite.

i just want the tool i depend on, which was taken over right before i saved it with enormous invested work, to not be destroyed by people who want to try out cool new things.

this is a core infrastructural piece of the internet.

everything about it should be boring and standard.  many of the rest of us are depending on it.
