### ISSUE TITLE
Drop the "size" optimize mode

### ISSUE THREAD

**Issue by Mingun** [peggyjs/peggy#92]
As I understand, David studied the construction of compilers, that is why he create a library with two possible implementations:
- statically generated functions ("speed" optimizing mode)
- interpreted bytecode ("size" optimizing mode)

Frankly speaking, size of the generated parsers in the "size" mode don't differ much from these parsers, generated in the "speed" mode, but their parsing speed is worse.

Generating in the "size" mode would be valuable if the generator had generated only bytecode instructions; but it is also generating the interpreter, which for small grammars don't differ much in the size from the grammars, generated in the "speed" mode.

Judging that, there is no reasons to keep the "size" mode, so I suggest to drop it. I think, that nobody uses that mode.

**Comment by hildjj** [comment]
Presumably, the option would still be legal, but ignored (at least for now)?

(leaving open the possibility we come up with a completely different optimization later)

**Comment by StoneCypher** [comment]
I think it would be good to fix the whitespace issues and other things like that before we make a decision here.  After that the decision may look similar or may look different

I think Mingun is probably right, but re-adding it afterwards would be brutal

**Comment by hildjj** [comment]
> I think it would be good to fix the whitespace issues and other things like that before we make a decision here. After that the decision may look similar or may look different

SGTM.  Depends on #65 then, and perhaps #68.
