### ISSUE TITLE
AUTHORS file

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#93]
Peg is no longer a single author project.

I recommend we create [an AUTHORS file](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#people-fields-author-contributors), leave David as the first name, and include anyone who's ever committed a non-trivial PR.  There used to be a multi-author in package format, but nobody supports it, so it was taken out.

It would help this community to begin to grow again for people to feel some piece of ownership, both for their past and hopefully their future work.

I'd be happy to do the basics, but I'll want the community's help in adding their names

**Comment by hildjj** [comment]
Agree. https://github.com/peggyjs/peggy/blob/main/AUTHORS is what I came up with by looking at the git logs and piecing together what GitHub account names I could.

**Comment by hildjj** [comment]
Also, I think I got all of the copyright statements pointing that way, but I didn't put in links, which would make it more explicit.

**Comment by StoneCypher** [comment]
oh god there already is one, that's embarrassing
