### ISSUE TITLE
Browserify doesn't build under Windows

### ISSUE THREAD

**Issue by StoneCypher** [peggyjs/peggy#96]
When commands are prefaced with a runner to resolve #94, we get here:

![image](https://user-images.githubusercontent.com/77482/115759730-6e1eec00-a355-11eb-9226-b67a8424fa92.png)

Not actually going to fix it; instead going to replace it with #83

**Comment by Mingun** [comment]
It seems that node under Windows gets in `f` glob pattern `browser/*`, and under Linux that pattern is expanded by the shell.
